export const WISDOMS = [
  "Ein aufgeräumtes Zuhause ist ein aufgeräumter Geist.",
  "Wer Ordnung hält, hat mehr Zeit für das Schöne im Leben.",
  "Kleine Aufgaben – grosse Wirkung.",
  "Heute erledigt, morgen entspannt.",
  "Zusammen macht auch die langweiligste Aufgabe Spass.",
  "Der beste Weg, eine Aufgabe zu beginnen, ist, sie einfach anzufangen.",
  "Wer fleissig sät, wird reichlich ernten.",
  "Ein sauberes Haus ist ein glückliches Haus.",
  "Jede erledigte Aufgabe ist ein kleiner Sieg.",
  "Die beste Zeit, etwas zu tun, ist jetzt.",
  "Ordnung ist das halbe Leben.",
  "Wer aufräumt, findet was er sucht.",
  "Das Schönste am Erledigen ist das gute Gefühl danach.",
  "Kleine Schritte führen zu grossen Zielen.",
  "Wer viel hilft, macht die Welt ein bisschen besser.",
  "Ein Lächeln macht die Arbeit leichter.",
  "Der fleissige Mensch hat immer Zeit.",
  "Gemeinsam sind wir stärker.",
  "Was du heute kannst besorgen, das verschiebe nicht auf morgen.",
  "Jede Aufgabe, die du erledigst, macht dich stolzer.",
  "Eine Tat ist besser als tausend Worte.",
  "Wer gibt, dem wird gegeben.",
  "Das Leben ist schön, wenn man hilft.",
  "Geduld und Fleiss brechen durch alle Hindernisse.",
  "Wer arbeitet, verdient seinen Erfolg.",
  "Ein freundliches Wort kostet nichts und bringt viel.",
  "Tue Gutes und rede davon nicht.",
  "Wer sich anstrengt, wächst daran.",
  "Der Weg ist das Ziel – auch beim Abwaschen.",
  "Heute getan, morgen gewonnen.",
  "Arbeit macht das Leben süss.",
  "Wer hilft, wird gemocht.",
  "Ein sauberer Tisch ist ein freier Kopf.",
  "Fleiss zahlt sich aus – immer.",
  "Das Zuhause dankt es dir.",
  "Jeder Handgriff zählt.",
  "Wer Verantwortung übernimmt, wächst.",
  "Ordnung bringt Freiheit.",
  "Du bist grossartig – mach weiter so!",
  "Wer heute hilft, darf morgen faulenzen.",
  "Die Familie ist ein Team.",
  "Zusammenhalten macht uns stark.",
  "Kleine Hände, grosse Hilfe.",
  "Wer erledigt, was er begonnen hat, ist ein Held.",
  "Das Beste kommt nach der Arbeit.",
  "Jeder Einsatz lohnt sich.",
  "Ein aufgeräumter Raum gibt Kraft.",
  "Gemeinsam schaffen wir alles.",
  "Wer sich einsetzt, hinterlässt Spuren.",
  "Du machst einen Unterschied!",
] as const;

/** Returns the wisdom for today (same all day, changes at midnight). */
export function getWisdomOfTheDay(): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return WISDOMS[dayOfYear % WISDOMS.length];
}
